### PR TITLE
introduce osgicheck-maven-plugin

### LINKED ISSUE #325: Tooling: Enforce best practices via osgicheck-maven-plugin
The recently released plugin https://github.com/apache/felix/tree/trunk/tools/osgicheck-maven-plugin enforces some best practices with regard to OSGi. It should be included in the build to emit helpful warning and also breaking the build in case of heavily violating best practices.

### PR DESCRIPTION
**Pull request by kwin**
This closes #325

### CODE REVIEW

**Comment by kwin** [comment]
@ghenzler: Please check the output of the plugin, the warnings seem reasonable to me. Would you mind fixing this?

**Comment by ghenzler** [comment]
@kwin fixed the warnings in a3e446f142209c

**Comment by kwin** [comment]
@ghenzler There is one warning left
`[WARNING] Component biz.netcentric.cq.tools.actool.history.impl.AcHistoryServiceImpl should use greedy for reference repository` (in https://api.travis-ci.org/v3/job/448411168/log.txt).

**Comment by ghenzler** [comment]
Fixed the last one 44dcb52b54053118 (leaving only https://issues.apache.org/jira/browse/FELIX-5971 as false-positive)

**Pull request merged**
