### PR TITLE
#681 Updated index name to match Cloud Manager new standards

### PR DESCRIPTION
**Pull request by diogopedreira**
Following https://github.com/Netcentric/accesscontroltool/issues/681, the existing index has been renamed in order to be compliant with Adobe's guidelines - https://docs.mktossl.com/docs/experience-manager-cloud-service/content/operations/indexing.html?lang=en#index-names.

Changes:

- Updated index name
- Adjusted filter.xml to point to the new name and updated the existing rules to map the approach applied in https://github.com/Netcentric/accesscontroltool/pull/638/files
- Updated QueryHelper.java to refer to the new index name.

### CODE REVIEW

**Comment by kwin** [comment]
According to https://docs.mktossl.com/docs/experience-manager-cloud-service/content/operations/indexing.html?lang=en#index-names the pattern needs to be

`<prefix>.<indexName>-<productVersion>-custom-<customVersion>`

**Comment by diogopedreira** [comment]
> According to https://docs.mktossl.com/docs/experience-manager-cloud-service/content/operations/indexing.html?lang=en#index-names the pattern needs to be
> 
> `<prefix>.<indexName>-<productVersion>-custom-<customVersion>`

@kwin I've followed the pattern that was on the error log and it seems that there are some discrepancies on the standard, on the build result I get

2023-12-22T13:55:26.399Z,Netcentric:accesscontroltool-oakindex-package:3.0.10,0,"Index definition detected at /oak:index/repACL-custom-1. Fully custom index names need to follow the pattern **<prefix>.<name>-custom-<version>, e.g. /oak:index/acme.indexName-custom-1,** to be compliant with AEM as a Cloud Service",Code Smell,Minor,,IndexValidFullyCustomName,"aem,cloud-service-compatibility",https://www.adobe.com/go/aem_cmcq_indexvalidfullycusto_en 

The URL that they present is now returning a 404 and in here we have a different definition:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/operations/indexing.html?lang=en#index-management-without-rolling-deployments

In any case I will take the one you mentioned as it seems to be the new one.

**Comment by kwin** [comment]
The pattern without product version makes a lot more sense to me. Thanks for pointing out the discrepancies in the documentation. If this version does not emit any warning in Cloud Manager I am fine with that

**Comment by kwin** [comment]
@diogopedreira Have you tried to deploy with the node name as proposed in this PR? Does it emit any warnings in CloudManager?

**Comment by kwin** [comment]
The unmodified index definition does no longer emit any issue in the code checks in Cloud Manager, therefore no need to change it right now.

**Pull request closed without merging**
